services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5000:5000"
    networks:
      - app-network

  price-service:
    build:
      context: ./price-service
    ports:
      - "5001:5001"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: crypto_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
