apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-service
  template:
    metadata:
      labels:
        app: price-service
    spec:
      containers:
      - name: price-service
        image: price-service:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: price-service
spec:
  selector:
    app: price-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
