name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build User Service
      run: docker build -t user-service:latest ./user-service/

    - name: Build Price Service
      run: docker build -t price-service:latest ./price-service/

    - name: Deploy to Minikube
      run: |
        minikube start
        eval $(minikube docker-env)
        docker build -t user-service:latest ./user-service/
        docker build -t price-service:latest ./price-service/
        kubectl apply -f ./kubernetes/persistent-volume.yaml
        kubectl apply -f ./kubernetes/user-service-blue.yaml
        kubectl apply -f ./kubernetes/price-service.yaml
        kubectl apply -f ./kubernetes/service.yaml

  blue-green-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Switch to Green
      run: kubectl apply -f ./kubernetes/user-service-green.yaml

    - name: Patch Service to Green
      run: |
        kubectl patch service user-price-service -p '{"spec":{"selector":{"version":"green"}}}'
